/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDiscountPanel.java
 *
 * Created on 19/08/2011, 09:49:02 AM
 */
package com.openbravo.pos.sales;

import com.openbravo.pos.forms.AppLocal;
import javax.swing.JLabel;

/**
 *Panel management for discounts on the sales window
 * @author Carlos Prieto - SmartJSP S.A.S.
 */
public class JInsurancePanel extends javax.swing.JPanel {

    /** Creates new form JDiscountPanel */
    public JInsurancePanel() {
        initComponents();
        initLabels();
    }

    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        unitInfo1 = new com.openbravo.pos.ticket.UnitInfo();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jInsuranceCompany = new javax.swing.JLabel();
        jPlan = new javax.swing.JLabel();
        jCopayPercentage = new javax.swing.JLabel();
        jCopayValue = new javax.swing.JLabel();
        jTotal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCovered = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSubtotal = new javax.swing.JLabel();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pos_messages"); // NOI18N
        jLabel2.setText(bundle.getString("insurance.copay_percentage")); // NOI18N

        jLabel3.setText(bundle.getString("insurance.total")); // NOI18N

        jLabel4.setText(bundle.getString("insurancep.copay_value")); // NOI18N

        jLabel5.setText(bundle.getString("insuranceCompany.name")); // NOI18N

        jLabel6.setText(bundle.getString("insurancePlan.name")); // NOI18N

        jInsuranceCompany.setText(bundle.getString("insuranceCompany.name")); // NOI18N

        jPlan.setText(bundle.getString("insuranceCompany.name")); // NOI18N

        jCopayPercentage.setText(bundle.getString("insuranceCompany.name")); // NOI18N

        jCopayValue.setText(bundle.getString("insuranceCompany.name")); // NOI18N

        jTotal.setText(bundle.getString("insuranceCompany.name")); // NOI18N

        jLabel7.setText(bundle.getString("insurance.covered")); // NOI18N

        jCovered.setText(bundle.getString("insuranceCompany.name")); // NOI18N

        jLabel8.setText(bundle.getString("insurance.subtotal")); // NOI18N

        jSubtotal.setText(bundle.getString("insuranceCompany.name")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jInsuranceCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCopayPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCopayValue, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(jCovered, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jInsuranceCompany))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jPlan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCopayPercentage))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCopayValue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jSubtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCovered))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTotal)
                    .addComponent(jLabel3))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jCopayPercentage;
    private javax.swing.JLabel jCopayValue;
    private javax.swing.JLabel jCovered;
    private javax.swing.JLabel jInsuranceCompany;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jPlan;
    private javax.swing.JLabel jSubtotal;
    private javax.swing.JLabel jTotal;
    private com.openbravo.pos.ticket.UnitInfo unitInfo1;
    // End of variables declaration//GEN-END:variables

    /**
     * initializes the labels
     */
    private void initLabels() {
    }

    public void setjCopayPercentage(String jCopayPercentage) {
        this.jCopayPercentage.setText(jCopayPercentage);
    }

    public void setjCopayValue(String jCopayValue) {
        this.jCopayValue.setText(jCopayValue);
    }

    public void setjCovered(String jCovered) {
        this.jCovered.setText(jCovered);
    }

    public void setjInsuranceCompany(String jInsuranceCompany) {
        this.jInsuranceCompany.setText(jInsuranceCompany);
    }

    public void setjPlan(String jPlan) {
        this.jPlan.setText(jPlan);
    }
    
    public void setjTotal(String jTotal) {
        this.jTotal.setText(jTotal);
    }  
    
    public void setjSubtotal(String jsubTotal) {
        this.jSubtotal.setText(jsubTotal);
    }  
    
}
