//    Openbravo POS is a point of sales application designed for touch screens.
//    Copyright (C) 2008-2009 Openbravo, S.L.
//    http://www.openbravo.com/product/pos
//
//    This file is part of Openbravo POS.
//
//    Openbravo POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    Openbravo POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with Openbravo POS.  If not, see <http://www.gnu.org/licenses/>.
package com.openbravo.pos.payment;

import com.ewallet.client.RestClient;
import com.ewallet.utilities.Util;
import java.awt.Component;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import com.openbravo.format.Formats;
import com.openbravo.pos.customers.CustomerInfoExt;
//import com.openbravo.pos.dao.VoucherDAO;
import com.openbravo.pos.forms.AppLocal;
import com.ewallet.entity.Voucher;
import com.openbravo.pos.util.RoundUtils;
import java.util.Calendar;
import javax.swing.JOptionPane;

public class JPaymentVoucher extends javax.swing.JPanel implements JPaymentInterface {

    private JPaymentNotifier m_notifier;
    private double m_dTicket;
    private double m_dTotal;
    private String m_sPaper; // "paperin", "paperout"
    // private String m_sCustomer; 

    /**
     * Creates new form JPaymentTicket
     */
    public JPaymentVoucher(JPaymentNotifier notifier, String sPaper) {

        m_notifier = notifier;
        m_sPaper = sPaper;

        initComponents();

        m_jTendered.addPropertyChangeListener("Edition", new RecalculateState());
        m_jTendered.addEditorKeys(m_jKeys);
        
    }

    public void activate(CustomerInfoExt customerext, double dTotal, String transID) {

        m_dTotal = dTotal;

        m_jTendered.reset();
        m_jTendered.activate();

        printState();
    }

    public Component getComponent() {
        return this;
    }

    public PaymentInfo executePayment() {
        //VoucherDAO.getInstance().updateStatus(txtID.getText(), 0);
        return new PaymentInfoTicket(m_dTicket, m_sPaper);
    }

    private void printState() {

        Double value = m_jTendered.getDoubleValue();
        if (value == null) {
            m_dTicket = 0.0;
        } else {
            m_dTicket = value;
        }

        //m_jMoneyEuros.setText(Formats.CURRENCY.formatValue(new Double(m_dTicket)));
        txtNominal.setText(Formats.CURRENCY.formatValue(new Double(m_dTicket)));
        txtID.setText(Formats.STRING.formatValue(String.CASE_INSENSITIVE_ORDER  ));
        int iCompare = RoundUtils.compare(m_dTicket, m_dTotal);

        // it is allowed to pay more
        //m_notifier.setStatus(m_dTicket > 0.0, iCompare >= 0);

        // nilai Voucher tidak boleh lebih besar dari nilai transaksi
        m_notifier.setStatus(m_dTicket > 0.0, iCompare == 0);
    }

    private class RecalculateState implements PropertyChangeListener {

        public void propertyChange(PropertyChangeEvent evt) {
            printState();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnCheck = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNominal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lbKet = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        m_jKeys = new com.openbravo.editor.JEditorKeys();
        jPanel1 = new javax.swing.JPanel();
        m_jTendered = new com.openbravo.editor.JEditorCurrencyPositive();

        setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(null);

        jLabel3.setText("ID");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(20, 80, 14, 16);

        txtID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIDFocusGained(evt);
            }
        });
        jPanel4.add(txtID);
        txtID.setBounds(120, 80, 150, 26);

        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });
        jPanel4.add(btnCheck);
        btnCheck.setBounds(280, 80, 51, 28);

        jLabel4.setText("Nominal");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(20, 120, 60, 16);
        jPanel4.add(txtNominal);
        txtNominal.setBounds(120, 120, 110, 26);

        jLabel5.setText("Keterangan");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(20, 160, 80, 16);
        jPanel4.add(lbKet);
        lbKet.setBounds(120, 160, 280, 40);

        add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.Y_AXIS));
        jPanel12.add(m_jKeys);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(m_jTendered, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel1);

        jPanel11.add(jPanel12, java.awt.BorderLayout.NORTH);

        add(jPanel11, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
    try {
        //Voucher v = VoucherDAO.getInstance().find(txtID.getText());
        Voucher v = null;
        String va = RestClient.getVoucher(txtID.getText());
        if (!va.contains(":-1")) {
            v = Util.gson.fromJson(va, Voucher.class);
        }
        if (v == null) {
            lbKet.setText("Voucher Tidak ditemukan");
        } else {
            if (v.getStatus() == 0) {
                lbKet.setText("Voucher sudah  digunakan");
            } else if (v.getStatus() == 1) {

                if (v.getStartDate().getTime() > Calendar.getInstance().getTime().getTime()) {
                    lbKet.setText("Voucher belum berlaku");
                } else if (v.getEndDate().getTime() < Calendar.getInstance().getTime().getTime()) {
                    lbKet.setText("Voucher sudah Kadaluarsa");
                } else {
                    lbKet.setText("Voucher valid");
                    //txtNominal.setText(String.valueOf(v.getNominal()));
                    txtNominal.setText(Formats.CURRENCY.formatValue(new Double(v.getNominal())));
                }

            }
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
}//GEN-LAST:event_btnCheckActionPerformed

    private void txtIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDFocusGained
        // TODO add your handling code here:
        m_jTendered.activate();
    }//GEN-LAST:event_txtIDFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbKet;
    private com.openbravo.editor.JEditorKeys m_jKeys;
    private com.openbravo.editor.JEditorCurrencyPositive m_jTendered;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNominal;
    // End of variables declaration//GEN-END:variables
}
